import React from 'react';

export const TermsPage: React.FC = () => {
  return (
    <div style={{ minHeight: '100vh', background: '#f9fafb', padding: '48px 24px' }}>
      <div style={{ maxWidth: 720, margin: '0 auto', background: '#fff', borderRadius: 16, padding: '48px 56px', boxShadow: '0 1px 4px rgba(0,0,0,0.08)' }}>

        {/* Header */}
        <a href="/" style={{ display: 'inline-flex', alignItems: 'center', gap: 6, color: '#6d28d9', textDecoration: 'none', fontSize: 14, marginBottom: 32 }}>
          ← Back to findmewith.ai
        </a>
        <h1 style={{ fontSize: 32, fontWeight: 700, color: '#1e1b4b', marginBottom: 8 }}>Terms of Service</h1>
        <p style={{ color: '#6b7280', fontSize: 14, marginBottom: 40 }}>Last updated: June 2025</p>

        <p style={{ color: '#374151', lineHeight: 1.7, marginBottom: 24 }}>
          These terms govern your use of findmewith.ai, a product of GenieRocket LLC. By creating an account
          or using our service, you agree to these terms. We've written them in plain English — if anything
          is unclear, just ask at{' '}
          <a href="mailto:hello@findmewith.ai" style={{ color: '#6d28d9' }}>hello@findmewith.ai</a>.
        </p>

        <Section title="What findmewith.ai does">
          <p style={{ color: '#374151', lineHeight: 1.7 }}>
            findmewith.ai analyzes your website's visibility to AI-powered search engines (like ChatGPT,
            Perplexity, and Google AI Overviews) and gives you a score, actionable recommendations,
            and code snippets to help you improve. Results are based on publicly available signals from
            your website and third-party keyword data.
          </p>
        </Section>

        <Section title="Your account">
          <ul style={{ color: '#374151', lineHeight: 1.9, paddingLeft: 20 }}>
            <li>You must provide a valid email address to create an account.</li>
            <li>You're responsible for keeping your password secure.</li>
            <li>One account per person or business. You may not share accounts.</li>
            <li>You must be 18 or older to use findmewith.ai.</li>
          </ul>
        </Section>

        <Section title="Free plan">
          <p style={{ color: '#374151', lineHeight: 1.7 }}>
            The free scan gives you your AI visibility score and a summary of issues. Some features
            (like the AI Content Writer and full Code Snippets library) require a Pro subscription.
            The monitoring widget script is free with basic signals; advanced signals require Pro.
          </p>
        </Section>

        <Section title="Pro and Agency subscriptions">
          <ul style={{ color: '#374151', lineHeight: 1.9, paddingLeft: 20 }}>
            <li>Pro is $29/month or $249/year. Agency is $99/month or $999/year.</li>
            <li>Subscriptions renew automatically. You can cancel any time from your account settings.</li>
            <li>If you cancel, you keep Pro access until the end of your billing period.</li>
            <li>We offer a 7-day money-back guarantee. Email us within 7 days of your first payment if you're not satisfied.</li>
            <li>Prices may change with 30 days' notice by email.</li>
          </ul>
        </Section>

        <Section title="Acceptable use">
          <p style={{ color: '#374151', lineHeight: 1.7 }}>
            You agree to use findmewith.ai only for lawful purposes. You may not:
          </p>
          <ul style={{ color: '#374151', lineHeight: 1.9, paddingLeft: 20, marginTop: 8 }}>
            <li>Scan websites you don't own or have explicit permission to analyze.</li>
            <li>Attempt to reverse-engineer, scrape, or abuse the API.</li>
            <li>Use the service to harm, deceive, or spam others.</li>
          </ul>
        </Section>

        <Section title="Accuracy of results">
          <p style={{ color: '#374151', lineHeight: 1.7 }}>
            Our AI visibility scores are based on the best available signals and keyword data, but
            they are estimates — not guarantees. AI search engines are evolving rapidly, and no tool
            can perfectly predict how any given platform will rank or surface content. Results should
            be used as a guide, not as a definitive audit.
          </p>
        </Section>

        <Section title="Our content">
          <p style={{ color: '#374151', lineHeight: 1.7 }}>
            The code snippets, schema markup, llms.txt templates, and other content generated by
            findmewith.ai are provided for your use on your own website. We don't claim copyright
            over output you generate with the tool.
          </p>
        </Section>

        <Section title="Limitation of liability">
          <p style={{ color: '#374151', lineHeight: 1.7 }}>
            findmewith.ai is provided "as is." To the fullest extent allowed by law, GenieRocket LLC
            is not liable for any indirect, incidental, or consequential damages arising from your
            use of the service. Our total liability is limited to the amount you paid us in the
            three months before the claim.
          </p>
        </Section>

        <Section title="Changes to these terms">
          <p style={{ color: '#374151', lineHeight: 1.7 }}>
            We may update these terms occasionally. If changes are material, we'll notify you by
            email at least 14 days before they take effect. Continued use after that date means
            you accept the updated terms.
          </p>
        </Section>

        <Section title="Governing law">
          <p style={{ color: '#374151', lineHeight: 1.7 }}>
            These terms are governed by the laws of the State of Utah, United States.
            Any disputes will be resolved in courts located in Utah County, Utah.
          </p>
        </Section>

        <Section title="Contact">
          <p style={{ color: '#374151', lineHeight: 1.7 }}>
            GenieRocket LLC — <a href="mailto:hello@findmewith.ai" style={{ color: '#6d28d9' }}>hello@findmewith.ai</a>
          </p>
        </Section>

      </div>
    </div>
  );
};

const Section: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => (
  <div style={{ marginBottom: 36 }}>
    <h2 style={{ fontSize: 18, fontWeight: 700, color: '#1e1b4b', marginBottom: 12, paddingBottom: 8, borderBottom: '1px solid #f3f4f6' }}>
      {title}
    </h2>
    {children}
  </div>
);

export default TermsPage;
